#!/usr/bin/env python3
"""Generate one real HTML file per post, so /<slug> is a 200 with its own metadata.

GitHub Pages resolves an extensionless request to `<path>.html`, so `<slug>.html`
at the repo root is served at `/<slug>` directly — no redirect, no trailing slash,
no visible extension. That is the URL people copy.

The site itself stays a client-side app: each generated page loads the same CSS and
JS as the root index.html, and app.js works out which post to render from the path.
The only thing that differs per page is the <head> — title, description, canonical,
and the Open Graph / Twitter tags that link previews and crawlers read, none of which
can be filled in by JavaScript because those readers do not run any.

Run from the repo root, before committing:

    python3 build_pages.py

Pages belonging to posts that have been removed from posts.json are deleted.
"""

import html
import json
import pathlib
import shutil
import sys

ROOT = pathlib.Path(__file__).parent
SITE_URL = "https://haotianfang.com"
SITE_NAME = "Haotian Fang"

TEMPLATE = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title} · {site}</title>
  <meta name="description" content="{summary}">
  <link rel="canonical" href="{url}">
  <meta property="og:site_name" content="{site}">
  <meta property="og:type" content="article">
  <meta property="og:url" content="{url}">
  <meta property="og:title" content="{title}">
  <meta property="og:description" content="{summary}">
  <meta property="article:published_time" content="{created}">
  <meta property="article:modified_time" content="{updated}">
  <meta property="article:author" content="{site}">
  <meta name="twitter:card" content="summary">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont/style.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fontsource/noto-nastaliq-urdu/arabic.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fontsource/klee-one/japanese.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css">
  <link rel="stylesheet" href="/assets/style.css">
</head>
<body>
  <main id="app"><p class="loading">…</p></main>
  <noscript><h1>{title}</h1><p>{summary}</p><p><a href="/{file}">Read this post as plain Markdown</a>.</p></noscript>
  <script src="/assets/marked.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"></script>
  <script src="/assets/app.js"></script>
</body>
</html>
"""

# a file is ours to manage only if it starts with this line
MARKER = "<!-- generated by build_pages.py -->\n"

# a slug must never shadow something the site actually serves
RESERVED = {"index", "assets", "posts", "404", "CNAME"}


def main() -> int:
    posts = json.loads((ROOT / "posts.json").read_text(encoding="utf-8"))
    wanted = set()

    for p in posts:
        slug = p["slug"]
        wanted.add(slug)
        page = TEMPLATE.format(
            site=SITE_NAME,
            file=html.escape(p.get("file", f"posts/{slug}.md"), quote=True),
            url=f"{SITE_URL}/{slug}",
            title=html.escape(p.get("title", slug), quote=True),
            summary=html.escape(p.get("summary", ""), quote=True),
            created=p.get("created", ""),
            updated=p.get("updated", p.get("created", "")),
        )
        if slug in RESERVED:
            raise SystemExit(f"slug {slug!r} collides with a real path in the repo")
        (ROOT / f"{slug}.html").write_text(MARKER + page, encoding="utf-8")
        print(f"  wrote {slug}.html")

    # drop pages for posts that no longer exist (and any directory left by the
    # earlier /<slug>/index.html scheme)
    for entry in ROOT.iterdir():
        if entry.name.startswith((".", "_")):
            continue
        if entry.is_file() and entry.suffix == ".html" and entry.stem not in wanted:
            if entry.read_text(encoding="utf-8").startswith(MARKER):
                entry.unlink()
                print(f"  removed stale {entry.name}")
        elif entry.is_dir():
            idx = entry / "index.html"
            if idx.is_file() and idx.read_text(encoding="utf-8").startswith(MARKER):
                shutil.rmtree(entry)
                print(f"  removed stale {entry.name}/ (old scheme)")

    print(f"{len(wanted)} page(s) generated.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
