#!/usr/bin/env python3
"""Generate one real HTML file per post, so /<slug> is a 200 with its own metadata.

GitHub Pages resolves an extensionless request to `<path>.html`, so `<slug>.html`
at the repo root is served at `/<slug>` directly — no redirect, no trailing slash,
no visible extension. That is the URL people copy.

The learning map's notes work the same way one level down: `learning/<slug>.html`
is served at `/learning/<slug>`. They are listed in `learning.json`, never in
`posts.json`, which is what keeps them out of the home list and the site-wide search.

The site itself stays a client-side app: each generated page loads the same CSS and
JS as the root index.html, and app.js works out which post to render from the path.
The only thing that differs per page is the <head> — title, description, canonical,
and the Open Graph / Twitter tags that link previews and crawlers read, none of which
can be filled in by JavaScript because those readers do not run any.

Run from the repo root, before committing:

    python3 build_pages.py

Pages belonging to posts or notes that have been removed from their manifest are
deleted. The manifests are validated first; a broken one stops the build.
"""

import html
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).parent
SITE_URL = "https://haotianfang.com"
SITE_NAME = "Haotian Fang"

# the learning map: manifest at the root, notes one directory down
MAP_FILE = "learning.json"
MAP_SLUG = "learning-map"
NOTE_DIR = "learning"

TEMPLATE = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title} · {site}</title>
  <meta name="description" content="{summary}">
  <link rel="canonical" href="{url}">
  <meta property="og:site_name" content="{site}">
  <meta property="og:type" content="article">
  <meta property="og:url" content="{url}">
  <meta property="og:title" content="{title}">
  <meta property="og:description" content="{summary}">
  <meta property="article:published_time" content="{created}">
  <meta property="article:modified_time" content="{updated}">
  <meta property="article:author" content="{site}">
  <meta name="twitter:card" content="summary">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont/style.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fontsource/noto-nastaliq-urdu/arabic.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fontsource/klee-one/japanese.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css">
  <link rel="stylesheet" href="/assets/style.css">
</head>
<body>
  <main id="app"><p class="loading">…</p></main>
  <noscript><h1>{title}</h1><p>{summary}</p><p><a href="/{file}">Read this post as plain Markdown</a>.</p></noscript>
  <script src="/assets/marked.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"></script>
  <script src="/assets/app.js"></script>
</body>
</html>
"""

# a file is ours to manage only if it starts with this line
MARKER = "<!-- generated by build_pages.py -->\n"

# a slug must never shadow something the site actually serves
RESERVED = {"index", "assets", "posts", "404", "CNAME", NOTE_DIR}
# inside learning/, only a directory index would be shadowed
RESERVED_NOTE = {"index"}

SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


def die(msg):
    raise SystemExit("build_pages: " + msg)


def page(entry, slug, url, file):
    """The <head> is the only thing that differs per page; fill it from the manifest.

    `file` is passed in rather than defaulted here: posts live at posts/<slug>.md and
    notes at posts/learning/<slug>.md, and a default that guessed wrong would produce
    a page that builds cleanly with a 404 behind its only noscript link."""
    return MARKER + TEMPLATE.format(
        site=SITE_NAME,
        file=html.escape(file, quote=True),
        url=url,
        title=html.escape(entry.get("title", slug), quote=True),
        summary=html.escape(entry.get("summary", ""), quote=True),
        created=entry.get("created", ""),
        updated=entry.get("updated", entry.get("created", "")),
    )


def frontmatter(path):
    """Just enough YAML to compare a note's own header against the manifest."""
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\r?\n(.*?)\r?\n---", text, re.S)
    if not m:
        return {}
    meta = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, _, v = line.partition(":")
            meta[k.strip()] = v.strip().strip("\"'")
    return meta


def sweep(directory, wanted, label):
    """Delete generated pages whose entry is gone; never touch a file we did not write."""
    if not directory.is_dir():
        return
    for entry in sorted(directory.iterdir()):
        if entry.is_file() and entry.suffix == ".html" and entry.stem not in wanted:
            if entry.read_text(encoding="utf-8").startswith(MARKER):
                entry.unlink()
                print(f"  removed stale {label}{entry.name}")


def load_map():
    """Read and check learning.json. A broken map stops the build: every failure here
    is one that would otherwise show up as a note silently missing from the graph."""
    path = ROOT / MAP_FILE
    if not path.exists():
        return [], []
    data = json.loads(path.read_text(encoding="utf-8"))
    nodes = data.get("nodes", [])
    edges = data.get("edges", [])
    if not isinstance(nodes, list) or not isinstance(edges, list):
        die(f"{MAP_FILE}: `nodes` and `edges` must both be lists")

    seen = set()
    for n in nodes:
        slug = n.get("slug", "")
        if not SLUG_RE.match(slug):
            die(f"{MAP_FILE}: note slug {slug!r} must be lowercase kebab-case ASCII")
        if slug in RESERVED_NOTE:
            die(f"{MAP_FILE}: note slug {slug!r} collides with a real path under {NOTE_DIR}/")
        if slug in seen:
            die(f"{MAP_FILE}: note slug {slug!r} is listed twice")
        seen.add(slug)

        rel = n.setdefault("file", f"posts/{NOTE_DIR}/{slug}.md")
        # the manifest is hand-edited; a path that walks out of the repo would be read
        # at build time and emitted as an off-site link in the generated page
        if rel.startswith("/") or ".." in pathlib.PurePosixPath(rel).parts \
                or not rel.startswith("posts/"):
            die(f"{MAP_FILE}: note {slug!r} has file {rel!r}; it must be a relative path under posts/")
        src = ROOT / rel
        if not src.is_file():
            die(f"{MAP_FILE}: note {slug!r} points at {rel}, which does not exist")
        meta = frontmatter(src)
        # compare with "" on both sides: a field present in one place and missing in the
        # other is drift too, and the silent case — it builds an empty <meta description>
        for field in ("title", "created", "updated", "summary"):
            if meta.get(field, "") != n.get(field, ""):
                print(f"  ! {slug}: {field} differs — {MAP_FILE} says {n.get(field, '')!r}, "
                      f"the frontmatter says {meta.get(field, '')!r}")

    for e in edges:
        a, b = e.get("from"), e.get("to")
        if a not in seen or b not in seen:
            die(f"{MAP_FILE}: edge {a!r} → {b!r} names a note that is not in `nodes`")
        if a == b:
            die(f"{MAP_FILE}: edge {a!r} → {b!r} is a self-loop")
    return nodes, edges


def main() -> int:
    posts = json.loads((ROOT / "posts.json").read_text(encoding="utf-8"))
    wanted = set()

    for p in posts:
        slug = p["slug"]
        if slug in RESERVED:
            die(f"slug {slug!r} collides with a real path in the repo")
        wanted.add(slug)
        (ROOT / f"{slug}.html").write_text(
            page(p, slug, f"{SITE_URL}/{slug}", p.get("file", f"posts/{slug}.md")), encoding="utf-8")
        print(f"  wrote {slug}.html")

    nodes, edges = load_map()
    if nodes and MAP_SLUG not in wanted:
        print(f"  ! {MAP_FILE} has {len(nodes)} note(s) but posts.json has no {MAP_SLUG!r} "
              f"record, so nothing links to them")

    note_wanted = set()
    if nodes:
        (ROOT / NOTE_DIR).mkdir(exist_ok=True)
        for n in nodes:
            slug = n["slug"]
            note_wanted.add(slug)
            (ROOT / NOTE_DIR / f"{slug}.html").write_text(
                page(n, slug, f"{SITE_URL}/{NOTE_DIR}/{slug}", n["file"]), encoding="utf-8")
            print(f"  wrote {NOTE_DIR}/{slug}.html")

    sweep(ROOT / NOTE_DIR, note_wanted, f"{NOTE_DIR}/")
    if (ROOT / NOTE_DIR).is_dir() and not any((ROOT / NOTE_DIR).iterdir()):
        (ROOT / NOTE_DIR).rmdir()
        print(f"  removed empty {NOTE_DIR}/")

    # drop pages for posts that no longer exist (and any directory left by the
    # earlier /<slug>/index.html scheme)
    for entry in sorted(ROOT.iterdir()):
        if entry.name.startswith((".", "_")) or entry.name == NOTE_DIR:
            continue
        if entry.is_file() and entry.suffix == ".html" and entry.stem not in wanted:
            if entry.read_text(encoding="utf-8").startswith(MARKER):
                entry.unlink()
                print(f"  removed stale {entry.name}")
        elif entry.is_dir():
            # a leftover <slug>/index.html from the old scheme. Delete that one file and
            # then the directory only if nothing else is in it — the previous version
            # rmtree'd the whole directory on the strength of its index.html, which took
            # any hand-written file sitting beside it with no warning and no way back.
            idx = entry / "index.html"
            if idx.is_file() and idx.read_text(encoding="utf-8").startswith(MARKER):
                idx.unlink()
                try:
                    entry.rmdir()
                    print(f"  removed stale {entry.name}/ (old scheme)")
                except OSError:
                    print(f"  ! removed {entry.name}/index.html, but kept {entry.name}/ — "
                          f"it holds files this script did not write")

    print(f"{len(wanted)} page(s) and {len(note_wanted)} note(s) generated.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
